crop_threshold: 0.5
drop_threshold: 0.5
crop_heat_map_threshold: 0.8
drop_heat_map_threshold: 0.8
object_threshold: 0.5
beta: 0.05

num_class: 100
num_attentions: 32
initial_learning_rate: 0.001
lr_decay_steps: 2
lr_decay_rate: 0.9
initial_weight_decay: 0.00001
wd_decay_steps: 10
wd_decay_rate: 0.9
momentum: 0.9
num_epochs: 80
num_batch: 5
image_fmt: '.jpg'
is_shuffle: True
pre_trained_type: ''
resize_h_w: [299, 299]

dataset_name: 'cub'
image_dir: '/Users/jeongchaejin/Desktop/JCJ/datasets/CUB_200_2011/CUB_200_2011/images'
train_dir: '/Users/jeongchaejin/Desktop/JCJ/datasets/pangyo_people/train/'
valid_dir: '/Users/jeongchaejin/Desktop/JCJ/datasets/pangyo_people/valid/'
logs_dir: './logs'
ckpt_dir: './ckpt/'

ckpt_path: ''
train_log_fmt: 'wsdan_{}_train'
valid_log_fmt: 'wsdan_{}_valid'

